CREATE DATABASE CARNICERIA_;
USE CARNICERIA_;

USE MASTER
DROP DATABASE CARNICERIA_

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY,
NOMBRE_REFERENCIA VARCHAR(30),
NO_CELULAR VARCHAR(10),
COLONIA VARCHAR(30),
CALLE VARCHAR(30),
NO_EXTERIOR VARCHAR(10),
REFERENCIA VARCHAR(100));

INSERT INTO CLIENTE VALUES(1, 'MIRIAM ROMERO', '2212850149', 'JARDIN 16 DE SEPTIEMBRE', '1ERA PRIVADA B', '8911', 'FRENTE BODEGA AURRERA');
SELECT MAX(ID_CLIENTE) FROM CLIENTE
SELECT NOMBRE_REFERENCIA FROM CLIENTE; 
SELECT * FROM CLIENTE

CREATE TABLE CARNICERO(
ID_CARNICERO INT PRIMARY KEY,
NOMBRE VARCHAR(20),
PRIMER_APP VARCHAR(20));

INSERT INTO CARNICERO VALUES(1, 'CRISTOBAL', 'MORALES');
INSERT INTO CARNICERO VALUES(2, 'ALONSO', 'MARTINEZ');
INSERT INTO CARNICERO VALUES(3, 'MAURICIO', 'PERALTA');
INSERT INTO CARNICERO VALUES(4, 'MARTIN', 'OLIVARES');

CREATE TABLE REPARTIDORES(
ID_REPARTIDOR INT PRIMARY KEY,
NOMBRE VARCHAR(20),
PRIMER_APP VARCHAR(20),
TRANSPORTE VARCHAR(30));

INSERT INTO REPARTIDORES VALUES(1, 'ENRIQUE', 'ROMERO', 'MOTOCICLETA');
INSERT INTO REPARTIDORES VALUES(2, 'ROGELIO', 'TITLA', 'BICICLETA');

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT PRIMARY KEY,
PRODUCTO VARCHAR(30),
PRECIO FLOAT,
TIPO_CARNE VARCHAR(30));

INSERT INTO PRODUCTOS VALUES(1, 'PIERNA', 80.00, 'CERDO');
INSERT INTO PRODUCTOS VALUES(2, 'CHULETA', 60.00, 'CERDO');
INSERT INTO PRODUCTOS VALUES(3, 'COSTILLA', 90.00, 'CERDO');
INSERT INTO PRODUCTOS VALUES(4, 'FALDA', 70.00, 'RES');
INSERT INTO PRODUCTOS VALUES(5, 'CARNE MOLIDA', 60.00, 'RES');
INSERT INTO PRODUCTOS VALUES(6, 'BISTEC', 50.00, 'RES');


CREATE TABLE PEDIDOS(
ID_PEDIDO INT PRIMARY KEY,
ID_CLIENTE INT,
ID_CARNICERO INT,
ID_REPARTIDOR INT,
TIPO_PAGO VARCHAR(30),
FEFHA DATE,
TOTAL FLOAT,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY (ID_CARNICERO) REFERENCES CARNICERO (ID_CARNICERO),
FOREIGN KEY (ID_REPARTIDOR) REFERENCES REPARTIDORES (ID_REPARTIDOR));

INSERT INTO PEDIDOS VALUES(1, 1, 1, 1, 'TARJETA', GETDATE(), 0);
SELECT * FROM PEDIDOS

CREATE TABLE DETALLES_PEDIDOS(
ID_PEDIDO INT,
ID_PRODUCTO INT,
CANTIDAD INT,
PRECIO_TOTAL FLOAT,
FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO));

INSERT INTO DETALLES_PEDIDOS VALUES(1,1,3, 240.00);

select * from detalles_pedidos

CREATE TABLE ACLARACIONES(
ID_PEDIDO INT,
DESCRIPCION VARCHAR(20),
FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO));

SELECT PRODUCTO, PRECIO FROM PRODUCTOS WHERE TIPO_CARNE = 'RES'